### PR TITLE
Update runtime

### PR DESCRIPTION
**Pull request by razzeee**

### CODE REVIEW

**Comment by mbugni** [comment]
I'm not sure this old game can run with modern GZDoom: if I well remember latest engines dropped some features it relies on. I will try if I find some time.

**Comment by razzeee** [comment]
This shouldn't be a new gzdoom version. The question is if that old version of gzdoom works on recent Linux versions.

**Comment by mbugni** [comment]
> This shouldn't be a new gzdoom version.

No, this is an old version (4.10.0). But newer versions break the game.

> The question is if that old version of gzdoom works on recent Linux versions.

The issue is about compiler. I'm not a C++ expert, but is seems that recent compilers won't build this code.
I also tried [this patch](https://github.com/flathub/shared-modules/pull/265) but it doesn't work.

**Comment by mbugni** [comment]
Trying to update runtime using binaries on [this PR](https://github.com/flathub/com.moddb.TotalChaosRetro/pull/5).

**Pull request closed without merging**
