### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by mbugni**

### CODE REVIEW

**Comment by AsciiWolf** [comment]
Wow, the new icon looks great! Any chance you could make a similar icon for regular [Total Chaos](https://github.com/flathub/com.moddb.TotalChaos) Flatpak? :-)

**Review by AsciiWolf — APPROVED** [review]
Looks good! The .zip archive seems to be the same.

**Comment by mbugni** [comment]
> Wow, the new icon looks great! Any chance you could make a similar icon for regular [Total Chaos](https://github.com/flathub/com.moddb.TotalChaos) Flatpak? :-)

Sure! It's a simple ImageMagick effect:

```shell
$ magick original.png \
     \( +clone  -alpha extract \
        -draw 'fill black polygon 0,0 0,15 15,0 fill white circle 15,15 15,0' \
        \( +clone -flip \) -compose Multiply -composite \
        \( +clone -flop \) -compose Multiply -composite \
     \) -alpha off -compose CopyOpacity -composite  rounded_corners.png
```

I can do a PR.

**Comment by mbugni** [comment]
> Looks good! The .zip archive seems to be the same.

It's exactly the same. I'm going to remove old repo, since now is on Flathub. I'll keep the legacy version.

**Pull request merged**
