### PR TITLE
Update runtime 24.08 using GCC 14.2 patch

### PR DESCRIPTION
**Pull request by mbugni**

### CODE REVIEW

**Comment by mbugni** [comment]
Thanks to @0strodamus for [this comment](https://github.com/ZDoom/gzdoom/issues/2018#issuecomment-1955441491).  I finally get it working by applying [this patch](https://github.com/ZDoom/gzdoom/commit/b95dbaf914618cccaeaa95c650e02be669e477f8) and [this patch](https://github.com/flathub/shared-modules/pull/265).

**Comment by AsciiWolf** [comment]
Nice, great job! I will test it in upcoming days.

P.S. Any chance you could also make a PR for the [regular version](https://github.com/flathub/com.moddb.TotalChaos) of Total Chaos? :-)

**Comment by AsciiWolf** [comment]
Tested and seems to work fine except one small thing. Objects that can be picked up are appearing without textures:

screenshot

However, I did not test the old build (I have a slow internet connection here and no 22.08 runtime installed) so it is possible that it is an unrelated problem that may be caused by my old Intel GPU.

**Review by AsciiWolf — APPROVED** [review]

**Comment by razzeee** [comment]
Just checked, current version has the same bug.

**Comment by AsciiWolf** [comment]
Then it is ready to be merged. :-)

**Comment by mbugni** [comment]
> Tested and seems to work fine except one small thing. Objects that can be picked up are appearing without textures:

Which renderer (Video Mode > Preferred Renderer API) are you using? Please try also OpenGL ES

**Comment by AsciiWolf** [comment]
I am using the default renderer: OpenGL. Same issue with Vulkan.

Changing the renderer to OpenGL ES have fixed the issue.

**Comment by mbugni** [comment]
Yes, in order to better render/perform this game you need to play a bit with settings. It depends on GPU. If I play with Intel integrated GPU OpenGL ES is the best choice.
I think GZDoom players know this.

**Pull request merged**
