### PR TITLE
Update runtime using binaries

### PR DESCRIPTION
**Pull request by mbugni**

### CODE REVIEW

**Comment by mbugni** [comment]
@AsciiWolf @razzeee I confirm this game works with a 24.08 runtime. But it does not compile. To make it working I used binaries from 2022 and I provided missing libs. The issue is about compiler, the latest one won't bild this code. So we can use binaries, but we will lose ARM architecture.

**Comment by razzeee** [comment]
Doesn't sound fun :/
Do you know, what the compiler complains about?

**Comment by mbugni** [comment]
I commented [this issue](https://github.com/ZDoom/gzdoom/issues/2018).

**Comment by razzeee** [comment]
Interesting, I don't see that error in https://gcc.gnu.org/gcc-14/porting_to.html from a glance

**Comment by mbugni** [comment]
Applying [this patch](https://github.com/flathub/com.moddb.TotalChaosRetro/blob/77fc27c2fb708577c52ec8c6f1b83d3c83b89a9a/gcc14.patch) make compiling from sources working again

**Pull request closed without merging**
